"""Seed universe of ~150 liquid US tickers.

(ticker, company name, sector, approx market cap $B, approx float shares B).
Market cap / float are indicative seeds; live providers refresh them when the
key's tier allows. Used verbatim by sample mode.
"""

UNIVERSE: list[tuple[str, str, str, float, float]] = [
    # Mega-cap tech
    ("AAPL", "Apple Inc.", "Technology", 3200, 15.2),
    ("MSFT", "Microsoft Corp.", "Technology", 3100, 7.4),
    ("NVDA", "NVIDIA Corp.", "Technology", 3000, 23.5),
    ("GOOGL", "Alphabet Inc.", "Communication Services", 2100, 5.8),
    ("AMZN", "Amazon.com Inc.", "Consumer Discretionary", 1900, 9.0),
    ("META", "Meta Platforms Inc.", "Communication Services", 1300, 2.2),
    ("TSLA", "Tesla Inc.", "Consumer Discretionary", 800, 2.7),
    ("AVGO", "Broadcom Inc.", "Technology", 700, 4.6),
    ("ORCL", "Oracle Corp.", "Technology", 380, 1.6),
    ("CRM", "Salesforce Inc.", "Technology", 280, 0.96),
    ("AMD", "Advanced Micro Devices", "Technology", 250, 1.6),
    ("ADBE", "Adobe Inc.", "Technology", 240, 0.44),
    ("QCOM", "Qualcomm Inc.", "Technology", 190, 1.1),
    ("TXN", "Texas Instruments", "Technology", 180, 0.91),
    ("INTC", "Intel Corp.", "Technology", 130, 4.2),
    ("MU", "Micron Technology", "Technology", 120, 1.1),
    ("AMAT", "Applied Materials", "Technology", 170, 0.82),
    ("LRCX", "Lam Research", "Technology", 100, 0.13),
    ("KLAC", "KLA Corp.", "Technology", 90, 0.13),
    ("ADI", "Analog Devices", "Technology", 110, 0.49),
    ("NOW", "ServiceNow Inc.", "Technology", 160, 0.20),
    ("INTU", "Intuit Inc.", "Technology", 180, 0.28),
    ("IBM", "IBM Corp.", "Technology", 170, 0.92),
    ("CSCO", "Cisco Systems", "Technology", 200, 4.0),
    ("PANW", "Palo Alto Networks", "Technology", 110, 0.32),
    ("CRWD", "CrowdStrike Holdings", "Technology", 80, 0.23),
    ("SNOW", "Snowflake Inc.", "Technology", 45, 0.32),
    ("DDOG", "Datadog Inc.", "Technology", 40, 0.30),
    ("NET", "Cloudflare Inc.", "Technology", 30, 0.29),
    ("ZS", "Zscaler Inc.", "Technology", 28, 0.14),
    ("PLTR", "Palantir Technologies", "Technology", 60, 2.0),
    ("SMCI", "Super Micro Computer", "Technology", 30, 0.05),
    ("ARM", "Arm Holdings", "Technology", 140, 0.10),
    ("MRVL", "Marvell Technology", "Technology", 60, 0.86),
    ("ON", "ON Semiconductor", "Technology", 30, 0.42),
    ("SHOP", "Shopify Inc.", "Technology", 90, 1.1),
    ("UBER", "Uber Technologies", "Technology", 140, 2.0),
    ("ABNB", "Airbnb Inc.", "Consumer Discretionary", 90, 0.43),
    ("DASH", "DoorDash Inc.", "Consumer Discretionary", 45, 0.33),
    ("COIN", "Coinbase Global", "Financials", 55, 0.20),
    ("HOOD", "Robinhood Markets", "Financials", 18, 0.75),
    ("SQ", "Block Inc.", "Financials", 45, 0.55),
    ("PYPL", "PayPal Holdings", "Financials", 70, 1.05),
    ("SOFI", "SoFi Technologies", "Financials", 8, 0.95),
    # Financials
    ("JPM", "JPMorgan Chase", "Financials", 560, 2.9),
    ("BAC", "Bank of America", "Financials", 300, 7.0),
    ("WFC", "Wells Fargo", "Financials", 200, 3.5),
    ("GS", "Goldman Sachs", "Financials", 140, 0.33),
    ("MS", "Morgan Stanley", "Financials", 150, 1.2),
    ("C", "Citigroup Inc.", "Financials", 120, 1.9),
    ("SCHW", "Charles Schwab", "Financials", 130, 1.5),
    ("BLK", "BlackRock Inc.", "Financials", 130, 0.15),
    ("AXP", "American Express", "Financials", 160, 0.70),
    ("V", "Visa Inc.", "Financials", 550, 1.6),
    ("MA", "Mastercard Inc.", "Financials", 420, 0.83),
    ("BRK.B", "Berkshire Hathaway B", "Financials", 900, 1.3),
    ("KKR", "KKR & Co.", "Financials", 100, 0.60),
    ("BX", "Blackstone Inc.", "Financials", 100, 0.70),
    # Healthcare
    ("LLY", "Eli Lilly & Co.", "Healthcare", 700, 0.79),
    ("UNH", "UnitedHealth Group", "Healthcare", 480, 0.92),
    ("JNJ", "Johnson & Johnson", "Healthcare", 380, 2.4),
    ("ABBV", "AbbVie Inc.", "Healthcare", 300, 1.8),
    ("MRK", "Merck & Co.", "Healthcare", 260, 2.5),
    ("PFE", "Pfizer Inc.", "Healthcare", 150, 5.6),
    ("TMO", "Thermo Fisher Scientific", "Healthcare", 210, 0.38),
    ("ABT", "Abbott Laboratories", "Healthcare", 190, 1.7),
    ("DHR", "Danaher Corp.", "Healthcare", 170, 0.71),
    ("AMGN", "Amgen Inc.", "Healthcare", 150, 0.54),
    ("ISRG", "Intuitive Surgical", "Healthcare", 170, 0.35),
    ("GILD", "Gilead Sciences", "Healthcare", 100, 1.2),
    ("VRTX", "Vertex Pharmaceuticals", "Healthcare", 120, 0.26),
    ("REGN", "Regeneron Pharmaceuticals", "Healthcare", 80, 0.10),
    ("MRNA", "Moderna Inc.", "Healthcare", 15, 0.34),
    ("BIIB", "Biogen Inc.", "Healthcare", 25, 0.14),
    ("HIMS", "Hims & Hers Health", "Healthcare", 10, 0.17),
    # Consumer
    ("WMT", "Walmart Inc.", "Consumer Staples", 700, 4.3),
    ("COST", "Costco Wholesale", "Consumer Staples", 400, 0.44),
    ("PG", "Procter & Gamble", "Consumer Staples", 390, 2.3),
    ("KO", "Coca-Cola Co.", "Consumer Staples", 290, 3.9),
    ("PEP", "PepsiCo Inc.", "Consumer Staples", 230, 1.4),
    ("PM", "Philip Morris International", "Consumer Staples", 200, 1.6),
    ("MDLZ", "Mondelez International", "Consumer Staples", 90, 1.3),
    ("CL", "Colgate-Palmolive", "Consumer Staples", 75, 0.81),
    ("KMB", "Kimberly-Clark", "Consumer Staples", 45, 0.33),
    ("TGT", "Target Corp.", "Consumer Staples", 60, 0.46),
    ("HD", "Home Depot", "Consumer Discretionary", 380, 0.99),
    ("LOW", "Lowe's Companies", "Consumer Discretionary", 140, 0.56),
    ("MCD", "McDonald's Corp.", "Consumer Discretionary", 210, 0.72),
    ("SBUX", "Starbucks Corp.", "Consumer Discretionary", 100, 1.1),
    ("NKE", "Nike Inc.", "Consumer Discretionary", 110, 1.2),
    ("LULU", "Lululemon Athletica", "Consumer Discretionary", 40, 0.11),
    ("CMG", "Chipotle Mexican Grill", "Consumer Discretionary", 75, 1.36),
    ("BKNG", "Booking Holdings", "Consumer Discretionary", 160, 0.033),
    ("MAR", "Marriott International", "Consumer Discretionary", 70, 0.27),
    ("RCL", "Royal Caribbean Group", "Consumer Discretionary", 60, 0.25),
    ("CCL", "Carnival Corp.", "Consumer Discretionary", 30, 1.2),
    ("DKNG", "DraftKings Inc.", "Consumer Discretionary", 20, 0.45),
    ("RIVN", "Rivian Automotive", "Consumer Discretionary", 15, 0.95),
    ("LCID", "Lucid Group", "Consumer Discretionary", 7, 1.5),
    ("F", "Ford Motor Co.", "Consumer Discretionary", 45, 3.9),
    ("GM", "General Motors", "Consumer Discretionary", 55, 1.1),
    # Communication / media
    ("NFLX", "Netflix Inc.", "Communication Services", 300, 0.42),
    ("DIS", "Walt Disney Co.", "Communication Services", 200, 1.8),
    ("CMCSA", "Comcast Corp.", "Communication Services", 150, 3.8),
    ("T", "AT&T Inc.", "Communication Services", 140, 7.1),
    ("VZ", "Verizon Communications", "Communication Services", 170, 4.2),
    ("TMUS", "T-Mobile US", "Communication Services", 260, 1.1),
    ("RBLX", "Roblox Corp.", "Communication Services", 25, 0.55),
    ("SPOT", "Spotify Technology", "Communication Services", 100, 0.15),
    ("PINS", "Pinterest Inc.", "Communication Services", 20, 0.60),
    ("SNAP", "Snap Inc.", "Communication Services", 15, 1.4),
    # Industrials
    ("CAT", "Caterpillar Inc.", "Industrials", 170, 0.48),
    ("DE", "Deere & Co.", "Industrials", 110, 0.27),
    ("BA", "Boeing Co.", "Industrials", 110, 0.61),
    ("GE", "GE Aerospace", "Industrials", 180, 1.1),
    ("HON", "Honeywell International", "Industrials", 130, 0.65),
    ("UNP", "Union Pacific", "Industrials", 140, 0.61),
    ("UPS", "United Parcel Service", "Industrials", 110, 0.73),
    ("LMT", "Lockheed Martin", "Industrials", 110, 0.24),
    ("RTX", "RTX Corp.", "Industrials", 150, 1.3),
    ("NOC", "Northrop Grumman", "Industrials", 70, 0.14),
    ("ETN", "Eaton Corp.", "Industrials", 130, 0.40),
    ("EMR", "Emerson Electric", "Industrials", 65, 0.57),
    ("URI", "United Rentals", "Industrials", 45, 0.066),
    ("DAL", "Delta Air Lines", "Industrials", 30, 0.64),
    ("UAL", "United Airlines", "Industrials", 25, 0.33),
    ("AAL", "American Airlines", "Industrials", 9, 0.65),
    # Energy / materials / utilities
    ("XOM", "Exxon Mobil", "Energy", 480, 4.4),
    ("CVX", "Chevron Corp.", "Energy", 280, 1.8),
    ("COP", "ConocoPhillips", "Energy", 130, 1.2),
    ("SLB", "Schlumberger", "Energy", 60, 1.4),
    ("EOG", "EOG Resources", "Energy", 70, 0.58),
    ("OXY", "Occidental Petroleum", "Energy", 55, 0.75),
    ("DVN", "Devon Energy", "Energy", 25, 0.62),
    ("FSLR", "First Solar", "Energy", 20, 0.10),
    ("ENPH", "Enphase Energy", "Energy", 15, 0.13),
    ("LIN", "Linde plc", "Materials", 210, 0.48),
    ("FCX", "Freeport-McMoRan", "Materials", 60, 1.4),
    ("NEM", "Newmont Corp.", "Materials", 45, 1.15),
    ("NUE", "Nucor Corp.", "Materials", 40, 0.24),
    ("NEE", "NextEra Energy", "Utilities", 150, 2.0),
    ("DUK", "Duke Energy", "Utilities", 80, 0.77),
    ("SO", "Southern Co.", "Utilities", 90, 1.1),
    ("VST", "Vistra Corp.", "Utilities", 40, 0.34),
    ("CEG", "Constellation Energy", "Utilities", 70, 0.31),
    # Real estate / other
    ("PLD", "Prologis Inc.", "Real Estate", 110, 0.92),
    ("AMT", "American Tower", "Real Estate", 90, 0.47),
    ("SPG", "Simon Property Group", "Real Estate", 55, 0.33),
    ("MSTR", "MicroStrategy Inc.", "Technology", 40, 0.17),
    ("MARA", "Marathon Digital Holdings", "Technology", 6, 0.28),
    ("RIOT", "Riot Platforms", "Technology", 4, 0.29),
    ("AFRM", "Affirm Holdings", "Financials", 15, 0.28),
    ("UPST", "Upstart Holdings", "Financials", 4, 0.085),
    ("CELH", "Celsius Holdings", "Consumer Staples", 15, 0.18),
    ("ELF", "e.l.f. Beauty", "Consumer Staples", 8, 0.055),
    ("DELL", "Dell Technologies", "Technology", 80, 0.25),
    ("HPE", "Hewlett Packard Enterprise", "Technology", 25, 1.3),
]
