"""initial schema

Revision ID: 1bb7570d473d
Revises: 
Create Date: 2026-07-18 21:23:16.740830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1bb7570d473d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('float_shares', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symbols_ticker'), ['ticker'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_user_id'), ['user_id'], unique=False)

    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtests_user_id'), ['user_id'], unique=False)

    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe', 'ts')
    )
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.create_index('ix_candles_lookup', ['symbol_id', 'timeframe', 'ts'], unique=False)

    op.create_table('catalysts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalysts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalysts_symbol_id'), ['symbol_id'], unique=False)

    op.create_table('indicator_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('ema20', sa.Float(), nullable=True),
    sa.Column('ema50', sa.Float(), nullable=True),
    sa.Column('ema200', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('atr_pct', sa.Float(), nullable=True),
    sa.Column('avg_volume', sa.Float(), nullable=True),
    sa.Column('rel_volume', sa.Float(), nullable=True),
    sa.Column('support', sa.Float(), nullable=True),
    sa.Column('resistance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'ts')
    )
    with op.batch_alter_table('indicator_values', schema=None) as batch_op:
        batch_op.create_index('ix_indicators_lookup', ['symbol_id', 'ts'], unique=False)

    op.create_table('options_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('call_volume', sa.Float(), nullable=True),
    sa.Column('put_volume', sa.Float(), nullable=True),
    sa.Column('put_call_ratio', sa.Float(), nullable=True),
    sa.Column('avg_call_volume', sa.Float(), nullable=True),
    sa.Column('oi_change_pct', sa.Float(), nullable=True),
    sa.Column('unusual', sa.Boolean(), nullable=False),
    sa.Column('iv', sa.Float(), nullable=True),
    sa.Column('iv_change', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'ts')
    )
    with op.batch_alter_table('options_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_options_activity_symbol_id'), ['symbol_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('swing_score', sa.Float(), nullable=False),
    sa.Column('momentum_pts', sa.Float(), nullable=False),
    sa.Column('volatility_pts', sa.Float(), nullable=False),
    sa.Column('volume_pts', sa.Float(), nullable=False),
    sa.Column('breakout_pts', sa.Float(), nullable=False),
    sa.Column('options_pts', sa.Float(), nullable=False),
    sa.Column('catalyst_pts', sa.Float(), nullable=False),
    sa.Column('trend', sa.String(length=24), nullable=False),
    sa.Column('setup_label', sa.String(length=64), nullable=False),
    sa.Column('entry', sa.Float(), nullable=True),
    sa.Column('entry_high', sa.Float(), nullable=True),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('risk_pct', sa.Float(), nullable=True),
    sa.Column('reward_pct', sa.Float(), nullable=True),
    sa.Column('rr_ratio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'ts')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index('ix_scores_lookup', ['ts', 'swing_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_symbol_id'), ['symbol_id'], unique=False)

    op.create_table('snapshots',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('spread_pct', sa.Float(), nullable=True),
    sa.Column('prev_close', sa.Float(), nullable=True),
    sa.Column('day_change_pct', sa.Float(), nullable=True),
    sa.Column('day_volume', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symbol_id')
    )
    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider')
    )
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlists_user_id'), ['user_id'], unique=False)

    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_triggered_at'), ['triggered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_user_id'), ['user_id'], unique=False)

    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_trades_backtest_id'), ['backtest_id'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_items_watchlist_id'), ['watchlist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_watchlist_id'))

    op.drop_table('watchlist_items')
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_trades_backtest_id'))

    op.drop_table('backtest_trades')
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_triggered_at'))
        batch_op.drop_index(batch_op.f('ix_alert_events_rule_id'))

    op.drop_table('alert_events')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlists_user_id'))

    op.drop_table('watchlists')
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_api_keys_user_id'))

    op.drop_table('user_api_keys')
    op.drop_table('snapshots')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_symbol_id'))
        batch_op.drop_index('ix_scores_lookup')

    op.drop_table('scores')
    with op.batch_alter_table('options_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_options_activity_symbol_id'))

    op.drop_table('options_activity')
    with op.batch_alter_table('indicator_values', schema=None) as batch_op:
        batch_op.drop_index('ix_indicators_lookup')

    op.drop_table('indicator_values')
    with op.batch_alter_table('catalysts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalysts_symbol_id'))

    op.drop_table('catalysts')
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.drop_index('ix_candles_lookup')

    op.drop_table('candles')
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtests_user_id'))

    op.drop_table('backtests')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_user_id'))

    op.drop_table('alert_rules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symbols_ticker'))

    op.drop_table('symbols')
    # ### end Alembic commands ###
