"""add short interest and explosive signals

Revision ID: 34b13db5af41
Revises: 1bb7570d473d
Create Date: 2026-08-19 12:33:52.391406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '34b13db5af41'
down_revision: Union[str, None] = '1bb7570d473d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explosive_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('explosive_score', sa.Float(), nullable=False),
    sa.Column('catalyst_pts', sa.Float(), nullable=False),
    sa.Column('squeeze_pts', sa.Float(), nullable=False),
    sa.Column('float_pts', sa.Float(), nullable=False),
    sa.Column('iv_pts', sa.Float(), nullable=False),
    sa.Column('volume_pts', sa.Float(), nullable=False),
    sa.Column('catalyst_kind', sa.String(length=24), nullable=False),
    sa.Column('catalyst_headline', sa.Text(), nullable=False),
    sa.Column('catalyst_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'ts')
    )
    with op.batch_alter_table('explosive_signals', schema=None) as batch_op:
        batch_op.create_index('ix_explosive_lookup', ['ts', 'explosive_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_explosive_signals_symbol_id'), ['symbol_id'], unique=False)

    op.create_table('short_interest',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('short_pct_float', sa.Float(), nullable=True),
    sa.Column('days_to_cover', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symbol_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_interest')
    with op.batch_alter_table('explosive_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_explosive_signals_symbol_id'))
        batch_op.drop_index('ix_explosive_lookup')

    op.drop_table('explosive_signals')
    # ### end Alembic commands ###
