"""add catalyst verified flag

Revision ID: 4bb284327cee
Revises: 34b13db5af41
Create Date: 2026-08-19 14:48:01.413682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4bb284327cee'
down_revision: Union[str, None] = '34b13db5af41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing rows (both tables already have data
    # in production) — every pre-existing catalyst/signal is correctly
    # unverified, since verified sourcing didn't exist until this migration.
    with op.batch_alter_table('catalysts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))

    with op.batch_alter_table('explosive_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalyst_verified', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explosive_signals', schema=None) as batch_op:
        batch_op.drop_column('catalyst_verified')

    with op.batch_alter_table('catalysts', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
